version: "3.9" 
services:
  web:
    build: .
    ports:
      - "80:3000"
  database:
          image: vikaspramila/my-mysql:01
    environment:
            - MYSQL_USER=password
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=pass
    ports:
            - "3306:3306"
    volumes:
            - datavolume01:/var/lib/mysql
volumes:
  datavolume01: {}
